import { Rubik, Secular_One } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  subsets: ["latin", "hebrew"], // כולל תמיכה בעברית
  weight: ["300", "400", "500", "700", "900"], // משקלים נדרשים
  style: ["normal", "italic"], // סטיילים
  variable: "--font-rubik",
});

const secularOne = Secular_One({
  subsets: ["latin", "hebrew"], // כולל תמיכה בעברית
  weight: ["400"], // המשקל היחיד שזמין ל-Secular One
  variable: "--font-secular-one",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="he" dir="rtl">
      <body className={`${rubik.variable} ${secularOne.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
